export default {
    BOTTOM_BACKGROUND: '#FBEFE1',
    TAPES_BACKGROUND: '#FCDC70',
    TAPE1_BACKGROUND: '#ACD9AE',
    TAPE2_BACKGROUND: '#FBE47A',
    TAPE3_BACKGROUND: '#FEA4A2',
    CREATE_BACKGROUND: '#a5d4b7'
  };