export default {
    BOTTOM_BACKGROUND: '#FBEFE1',
    TAPES_BACKGROUND: '#FCDC70',
    TAPE1_BACKGROUND: '#ACD9AE',
    TAPE2_BACKGROUND: '#FBE47A',
    TAPE3_BACKGROUND: '#FEA4A2',
    CREATE_TEXT: '#a5d4b7',
    //CREATE_BACKGROUND: '#2E2E2E',
    CREATE_BACKGROUND: '#2D3E40',
    //CREATE_BACKGROUND: '#13191C',
    //CREATE_BACKGROUND: '#1F1F1F',
    CREATE_BORDER: '#737373'
  };